[project]
name = "vhi-tests"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.6.0"
dependencies = [
    "duckdb>=0.8.1",
    "matplotlib>=3.3.4",
    "numpy>=1.19.5",
    "pandas>=0.25.3",
    "pyarrow>=6.0.1",
    "requests>=2.27.1",
]
